apiVersion: v1
kind: Service
metadata:
  name: apache-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: apache
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
